In [23]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
pip install --upgrade tensorflow

  Created wheel for absl-py: filename=absl_py-0.9.0-cp37-none-any.whl size=121936 sha256=9aede94901c6e64e4156ca618170ed5458d7c2a367842d1ade57b1a93e9a1b4c
  Stored in directory: C:\Users\raina\AppData\Local\pip\Cache\wheels\8e\28\49\fad4e7f0b9a1227708cbbee4487ac8558a7334849cb81c813d
  Created wheel for termcolor: filename=termcolor-1.1.0-cp37-none-any.whl size=4835 sha256=2a9fc44a9f0ac771e59f668fcf0429fba24dc05a424f3c0b141af9dec55cb413
  Stored in directory: C:\Users\raina\AppData\Local\pip\Cache\wheels\7c\06\54\bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
Successfully built absl-py termcolor
  Found existing installation: scipy 1.3.1
    Uninstalling scipy-1.3.1:
      Successfully uninstalled scipy-1.3.1
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\users\\raina\\anaconda3\\lib\\site-packages\\~cipy\\integrate\\lsoda.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [3]:
tf.__version__

'2.1.0'

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [24]:
print(x_test)

[[-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
   1.62185911]
 [ 1.04501206 -0.61433742 -0.57427105 ...  0.66011376 -1.02429504
   0.504204  ]
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376  0.97628121
  -0.41865644]
 ...
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376 -1.02429504
   0.72775202]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
  -1.54162886]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376 -1.02429504
   1.62356528]]


In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [9]:
ann = tf.keras.models.Sequential()

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [12]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [14]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 107us/sample - loss: 0.5589 - accuracy: 0.7437
Epoch 2/100
8000/8000 [==============================] - 0s 38us/sample - loss: 0.4776 - accuracy: 0.7934
Epoch 3/100
8000/8000 [==============================] - 0s 35us/sample - loss: 0.4506 - accuracy: 0.7943
Epoch 4/100
8000/8000 [==============================] - 0s 34us/sample - loss: 0.4392 - accuracy: 0.7954
Epoch 5/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4333 - accuracy: 0.7958
Epoch 6/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4296 - accuracy: 0.7990
Epoch 7/100
8000/8000 [==============================] - 0s 34us/sample - loss: 0.4267 - accuracy: 0.8011
Epoch 8/100
8000/8000 [==============================] - 0s 36us/sample - loss: 0.4240 - accuracy: 0.8044
Epoch 9/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4214 - accuracy: 0.8075
Epoch 10/100
8000/8000 

8000/8000 [==============================] - 0s 37us/sample - loss: 0.3362 - accuracy: 0.8645
Epoch 78/100
8000/8000 [==============================] - 0s 36us/sample - loss: 0.3364 - accuracy: 0.8645
Epoch 79/100
8000/8000 [==============================] - 0s 39us/sample - loss: 0.3358 - accuracy: 0.8641
Epoch 80/100
8000/8000 [==============================] - 0s 40us/sample - loss: 0.3359 - accuracy: 0.8649
Epoch 81/100
8000/8000 [==============================] - 0s 40us/sample - loss: 0.3357 - accuracy: 0.8631
Epoch 82/100
8000/8000 [==============================] - 0s 41us/sample - loss: 0.3357 - accuracy: 0.8630
Epoch 83/100
8000/8000 [==============================] - 0s 41us/sample - loss: 0.3358 - accuracy: 0.8641
Epoch 84/100
8000/8000 [==============================] - 0s 42us/sample - loss: 0.3357 - accuracy: 0.8627
Epoch 85/100
8000/8000 [==============================] - 0s 44us/sample - loss: 0.3354 - accuracy: 0.8644
Epoch 86/100
8000/8000 [==========================

In [18]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.1306527]], dtype=float32)

In [19]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1529   66]
 [ 211  194]]


0.8615

In [29]:
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.


In [28]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [30]:
tf.__version__

'2.1.0'

In [32]:
import os
os.getcwd()

'C:\\Users\\raina\\Downloads\\Courses'

In [36]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
training_set = train_datagen.flow_from_directory(
        'dataset/training_set',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary')

Found 8000 images belonging to 2 classes.


In [37]:
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory(
        'dataset/test_set',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary')

Found 2000 images belonging to 2 classes.


In [38]:
cnn = tf.keras.models.Sequential()

In [39]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size = 3, activation='relu', input_shape=[64, 64, 3]))

In [40]:
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2, padding='valid'))

In [41]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation="relu"))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2, padding='valid'))

In [42]:
cnn.add(tf.keras.layers.Flatten())

In [43]:
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

In [44]:
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [45]:
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [46]:
cnn.fit(x = training_set, validation_data = test_set, epochs = 25)

  ...
    to  
  ['...']
  ...
    to  
  ['...']
Train for 250 steps, validate for 63 steps
Epoch 1/25
250/250 [==============================] - 61s 246ms/step - loss: 0.6724 - accuracy: 0.5804 - val_loss: 0.6295 - val_accuracy: 0.6700
Epoch 2/25
250/250 [==============================] - 60s 241ms/step - loss: 0.6087 - accuracy: 0.6693 - val_loss: 0.5620 - val_accuracy: 0.7290
Epoch 3/25
250/250 [==============================] - 58s 233ms/step - loss: 0.5705 - accuracy: 0.7039 - val_loss: 0.5916 - val_accuracy: 0.6975
Epoch 4/25
250/250 [==============================] - 55s 221ms/step - loss: 0.5374 - accuracy: 0.7247 - val_loss: 0.5336 - val_accuracy: 0.7405
Epoch 5/25
250/250 [==============================] - 58s 233ms/step - loss: 0.5183 - accuracy: 0.7400 - val_loss: 0.5414 - val_accuracy: 0.7235
Epoch 6/25
250/250 [==============================] - 58s 233ms/step - loss: 0.4907 - accuracy: 0.7580 - val_loss: 0.5668 - val_accuracy: 0.7105
Epoch 7/25
250/250 [=================

In [54]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('dataset/single_prediction/cat_or_dog_4.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
if result[0][0] == 1:
    prediction = 'dog'
else:
    prediction = 'cat'

In [55]:
print(prediction)

dog
